name: PushGitlab

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      env:
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}

    - name: Push To Gitlab
      run: |
        echo Starting to push repo to gitlab
        git config user.name "githubuser"
        git config user.email "github@users.noreply.github.com"
        git remote set-url origin "https://github:glpat-QsT2qWEGGb3ZdsefNHz8@git.grechka.digital/devops/test2.git"
        git push -f origin dev
