name: PushGitlab

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      env:
        grchrepo: ${{ secrets.GRCHREPO }}

    - name: Push To Gitlab
      run: |
        date_now=$(date "+%F-%H-%M-%S")
        echo Starting to push repo to gitlab
        git config user.name "githubuser"
        git config user.email 'github@users.noreply.github.com'
        git remote set-url origin ${grchrepo}
        git checkout -b dev
        git remote -v
        git push --set-upstream -f origin dev
