name: PushGitlab

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      # env:
      #   token: ${{ secrets.GITLAB_ACCESS_TOKEN }}

    - name: Push To Gitlab
      run: |
        date_now=$(date "+%F-%H-%M-%S")
        echo Starting to push repo to gitlab
        git config user.name "githubuser"
        git config user.email 'github@users.noreply.github.com'
        git remote set-url origin 'https://github:glpat-QsT2qWEGGb3ZdsefNHz8@git.grechka.digital/devops/test2.git'
        git remote -v
        git add .
        git commit -m "${date_now}"
        git push --set-upstream origin dev
